require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/**/*'
    - 'vendor/bundle/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/Debugger:
  DebuggerMethods:
    RubyJard:
      - jard

Metrics:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: false

# Rails

Rails/Delegate:
  Enabled: false

# RSpec

RSpec/FactoryBot/CreateList:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
